Update dart.yml

diff --git a/.github/workflows/dart.yml b/.github/workflows/dart.yml
--- a/.github/workflows/dart.yml
+++ b/.github/workflows/dart.yml
@@ -19,9 +19,13 @@ jobs:
 
       - name: Install CocoaPods dependencies
         run: |
-          cd ios
-          pod install
-        working-directory: ios
+          if [ -d "ios" ]; then
+            cd ios
+            pod install
+          else
+            echo "ios directory not found"
+            exit 1
+          fi
 
       - name: Clean build
         run: flutter clean
@@ -31,16 +35,16 @@ jobs:
 
       - name: Prepare IPA package
         run: |
-          mkdir Payload
-          mv build/ios/iphoneos/Runner.app Payload/
-          cd Payload
-          zip -qq -r -9 FlutterIpaExport.ipa Runner.app
+          mkdir -p build/ios/iphoneos/Payload
+          mv build/ios/iphoneos/Runner.app build/ios/iphoneos/Payload/
+          cd build/ios/iphoneos
+          zip -qq -r -9 FlutterIpaExport.ipa Payload/Runner.app
 
       - name: Upload binaries to release
         uses: svenstaro/upload-release-action@v2
         with:
           repo_token: ${{ secrets.GITHUB_TOKEN }}
-          file: Payload/FlutterIpaExport.ipa
+          file: build/ios/iphoneos/FlutterIpaExport.ipa
           tag: v1.0
           overwrite: true
           body: "This is the first release"
